### PR TITLE
[CSM-167] Create automatic REST api table documentation

### PR DESCRIPTION
**Pull request by ksaric**
Generated from `cardano-sl-0.3` branch.
It's equivalent to wallet API and is being generated automatically. Open for suggestions/fixes.

### CODE REVIEW

**Comment by ksaric** [comment]
@rockbmb I can see it renders correctly on Github - https://github.com/input-output-hk/cardano-docs.iohk.io/blob/feature/csm-167-create-automatic-REST-api-table-documentation/_docs/technical/2017-02-08-daedalus.md#wallet-frontend-api

**Comment by denisshevchenko** [comment]
Wait! And where is link to Swagger-generated API table? I mean https://cardano-docs.iohk.io/technical/wallet/api/

**Comment by denisshevchenko** [comment]
And where is the link to Swagger-generated API table? I mean https://cardano-docs.iohk.io/technical/wallet/api/.

**Comment by ksaric** [comment]
That's on https://cardano-docs.iohk.io/technical/wallet/
This should be a API client side. Even though it's probably missing some things right now.

**Comment by denisshevchenko** [comment]
Oh, sorry, it's my misunderstanding.

**Comment by rockbmb** [comment]
@ksaric By the way, can you try making the branch names a bit shorter? It's a pain to `checkout` to a branch whose name is some 10 words long.

**Comment by ksaric** [comment]
@rockbmb Heh, you got a point there. Sure, I'll try make them sort in the future.

**Comment by rockbmb** [comment]
@denisshevchenko Does this not conflitct with your work? If it does not, I'll merge this now.

**Comment by denisshevchenko** [comment]
No conflicts, you can merge it.

**Pull request merged**
